const productActions = {
  SIMPLE_ACTION: 'SIMPLE_ACTION',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS'
};

const overviewActions = {
  SET_OVERVIEW: 'SET_OVERVIEW',
  SET_SUMMARY: 'SET_SUMMARY',
  SET_SUBSCRIBED_INGREDIENTS: 'SET_SUBSCRIBED_INGREDIENTS',
  SET_WATCHED_INGREDIENTS: 'SET_WATCHED_INGREDIENTS'
};

const authActions = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  SET_TOKEN: 'SET_TOKEN',
  CLEAR_STATE: 'CLEAR_STATE',
  SET_ROLE: 'SET_ROLE'
};

export const Actions = {
  productActions,
  overviewActions,
  authActions
};
