const productActions = {
  SIMPLE_ACTION: 'SIMPLE_ACTION',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS'
};

const overviewActions = {
  SET_OVERVIEW: 'SET_OVERVIEW',
  SET_SUMMARY: 'SET_SUMMARY',
  SET_SUBSCRIBED_INGREDIENTS: 'SET_SUBSCRIBED_INGREDIENTS',
  SET_WATCHED_INGREDIENTS: 'SET_WATCHED_INGREDIENTS'
};

export const Actions = {
  productActions,
  overviewActions
};
