const productActions = {
  SIMPLE_ACTION: 'SIMPLE_ACTION',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS'
};

const overviewActions = {
  SET_OVERVIEW: 'SET_OVERVIEW',
  SET_SUMMARY: 'SET_SUMMARY',
  SET_SUBSCRIBED_INGREDIENTS: 'SET_SUBSCRIBED_INGREDIENTS',
  SET_WATCHED_INGREDIENTS: 'SET_WATCHED_INGREDIENTS'
};

const adminActions = {
  SET_REPORT: 'SET_REPORT',
  ADD_NEW_REPORT: 'ADD_NEW_REPORT',
  SELECT_REPORT: 'SELECT_REPORT',
  UPDATE_REPORT: 'UPDATE_REPORT'
};

export const Actions = {
  productActions,
  overviewActions,
  adminActions
};
